# Generated by Django 2.2.1 on 2019-05-31 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TvShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tvseries_name', models.CharField(max_length=100)),
                ('tvseries_icon', models.CharField(max_length=500)),
                ('lang', models.CharField(max_length=100)),
                ('release_year', models.CharField(max_length=100)),
                ('i_m_d_b', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_no', models.CharField(max_length=100)),
                ('release_year', models.CharField(max_length=100)),
                ('i_m_d_b', models.CharField(max_length=10)),
                ('tv_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tv_series.TvShow')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_name', models.CharField(max_length=100)),
                ('episode_download_link', models.CharField(max_length=500)),
                ('episode_icon', models.CharField(max_length=500)),
                ('i_m_d_b', models.CharField(max_length=10)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tv_series.Season')),
            ],
        ),
    ]
