# Generated by Django 2.2.1 on 2019-06-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_series', '0005_auto_20190602_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='episode_download_link_other1',
            field=models.CharField(default='#', max_length=1000),
        ),
    ]
