# Generated by Django 2.2.1 on 2019-06-07 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tv_series', '0006_episode_episode_download_link_other1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='episode_download_link_other1',
        ),
    ]
