# Generated by Django 2.2.1 on 2019-05-24 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_episode_movies_season_tvseries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='episode_no',
        ),
        migrations.DeleteModel(
            name='Movies',
        ),
        migrations.RemoveField(
            model_name='season',
            name='season',
        ),
        migrations.DeleteModel(
            name='Episode',
        ),
        migrations.DeleteModel(
            name='Season',
        ),
        migrations.DeleteModel(
            name='TvSeries',
        ),
    ]
