# Generated by Django 2.2.1 on 2019-05-31 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_episode_movies_season_tvseries'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='description',
            field=models.CharField(default=' - ', max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movies',
            name='i_m_d_b',
            field=models.CharField(default=' - ', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movies',
            name='lang',
            field=models.CharField(default=' English ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movies',
            name='release_year',
            field=models.CharField(default=' - ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tvseries',
            name='lang',
            field=models.CharField(default=' English ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tvseries',
            name='release_year',
            field=models.CharField(default=' - ', max_length=100),
            preserve_default=False,
        ),
    ]
