# Generated by Django 2.2.1 on 2019-05-31 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190531_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvseries',
            name='i_m_d_b',
            field=models.CharField(default=' - ', max_length=10),
            preserve_default=False,
        ),
    ]
