# Generated by Django 2.2.1 on 2019-05-31 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_tvseries_i_m_d_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='i_m_d_b',
            field=models.CharField(default=' - ', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='season',
            name='i_m_d_b',
            field=models.CharField(default=' - ', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='season',
            name='release_year',
            field=models.CharField(default=' - ', max_length=100),
            preserve_default=False,
        ),
    ]
