# Generated by Django 2.2.1 on 2019-06-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0009_auto_20190531_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=100)),
                ('video_icon', models.CharField(default='#', max_length=1000)),
                ('video_link', models.CharField(default='#', max_length=1000)),
                ('video_type', models.CharField(default='movie', max_length=1000)),
            ],
        ),
    ]
