# Generated by Django 2.2.1 on 2019-06-02 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featured',
            name='video_link',
        ),
    ]
