# Generated by Django 2.2.1 on 2019-05-31 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('movie_download_link', models.CharField(max_length=500)),
                ('movie_icon', models.CharField(max_length=500)),
                ('lang', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=5000)),
                ('i_m_d_b', models.CharField(max_length=10)),
                ('release_year', models.CharField(max_length=100)),
            ],
        ),
    ]
