# Generated by Django 2.2.1 on 2019-05-31 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.CharField(default='-', max_length=5000),
        ),
        migrations.AlterField(
            model_name='movie',
            name='i_m_d_b',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AlterField(
            model_name='movie',
            name='lang',
            field=models.CharField(default='English', max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_download_link',
            field=models.CharField(default='#', max_length=500),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_icon',
            field=models.CharField(default='#', max_length=500),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_year',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
