# Generated by Django 2.2.1 on 2019-05-31 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20190531_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_download_link',
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_download_link_1080',
            field=models.CharField(default='#', max_length=1000),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_download_link_480',
            field=models.CharField(default='#', max_length=1000),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_download_link_720',
            field=models.CharField(default='#', max_length=1000),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_download_link_other',
            field=models.CharField(default='#', max_length=1000),
        ),
    ]
