# Generated by Django 2.2.1 on 2019-06-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20190531_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('movie_icon', models.CharField(default='#', max_length=500)),
                ('movie_link', models.CharField(default='#', max_length=1000)),
            ],
        ),
    ]
